version: '3'
services:
    database:
        image: 'mongo'
        container_name: 'bezmakeup'
        environment:
            - MONGO_INITDB_DATABASE=bezmakeup
            - MONGO_INITDB_ROOT_USERNAME=bezmakeup
            - MONGO_INITDB_ROOT_PASSWORD=Password123456
        volumes:
            - ./init-mongo.js:/docker-entrypoint-initdb.d/init_mongo.js:ro
            - ./mongo-volume:/data/db
        ports:
            - '27017-27019:27017-27019'